name: Docker Image CI

on:
  push:
    branches-ignore: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the API Docker image
      run: docker build api --file api/api.DOCKERFILE --tag yolo-api:${{ github.sha }}
    - name: Build the trainer Docker image
      run: docker build trainer_image --file trainer_image/trainer.DOCKERFILE --tag yolo-trainer:${{ github.sha }}
